root_dir = "."

[command]
dev = [
  "python3 main.py",
  "ngrok http --url=admittedly-adequate-scorpion.ngrok-free.app 3000",
  "npx @tailwindcss/cli -i ./static/input.css -o ./static/style.css --minify",
]
prod = []
test = []

[exclude]
dir = [".git", "__pycache__"]
file = []
ext = []

# css:
# 	npx @tailwindcss/cli -i ./static/input.css -o ./static/style.css --watch
